### ISSUE TITLE
Contract Design Review

### ISSUE THREAD

**Issue by mudgen** [bosonprotocol/contracts#125]
I reviewed the contracts as of the most recent commit at this time. [Latest](https://github.com/bosonprotocol/contracts/tree/1a1049330082eb85c6622696c5e1741a3bf99116)

I found the general design of the contracts good and workable. 

I like the integration done between the ERC1155 and ERC721 tokens. This is done to convert an item from an order supply to a unique voucher.

I like how a uint8 is being used to store status information. It is flexible, being able to store/read up to 8 (or 7 in this case) boolean states in a gas efficient way.

Here are some ideas/suggestions/recommendations for improvements for a future version of the protocol:

1. Currently the protocol has four different payment methods. This is to handle different ETH and TKN variations. I suggest having one payment method internally within the protocol which is TKNTKN. Continue to have the ETH functions like `requestCreateOrderETHETH`  but alter them so that they simply wrap ETH with WETH and then handle payment the same way the TKN functions do. This way, once ETH is converted to WETH, all payments can be handled the same way in the protocol. This is the same approach some major protocols such as Uniswap and Aave have taken. However this approach may cost more gas.

1. I suggest using the latest production version of Solidity.

1. I suggest organizing the contracts using an EIP-2535 diamond.  Of course I am biased. I am also happy to support other organizational patterns. However I didn't suggest this just because of my bias. I suggest it for this reason: I see that a diamond would solve the same problems I see the current design trying to solve but with better organization potential. Specifically:
      * The BosonRouter.sol contract provides an address that can be used by user interfaces and other contracts to interact and use the protocol. However the contract bytecode size limit will limit how much protocol functionality this contract can expose. A diamond inherently provides a router, a single address for accessing the protocol, without any bytecode size limitation.
      * VoucherKernel.sol is a grab bag of functionality. This is fine because the amount of functionality is not too much. Organization is more important the larger a system gets. A diamond provides a natural way to organize functionality that scales up. Here is how it can be organized:
           * Similar and related functions can be put in the same facet.
           * Similar and related facets can be put in the same folder.
           * Similar and related folders can be put in the same parent folder. 
      * VoucherKernel.sol contains 11 external functions with internal functionality that is not meant to be called by contracts outside the protocol and not meant to be called by user interfaces and other software. Cashier.sol contains 5 external functions with internal functionality that is not meant to be called by contracts outside the protocol and not meant to be called by user interfaces and other software. If a diamond was used then all internal functionality would use internal functions and all external functions would exist for external software to access the protocol.

Note that diamonds can be immutable and offer the same immutability and trustless guarantees as a regular immutable contract.

### Upgradeable Contracts

The Boson documentation says that the Boson protocol is a [system of non-upgradeable contracts](https://docs.bosonprotocol.io/protocol-overview/how-boson-works/). However this is not true in the current implementation. The documentation also implies that the smart contracts are trustless which is not true in the current implementation.

* The owner of the `ERC1155ERC721` contract can change the KernelAddress and the CashierAddress. With this power the owner can mint or burn users' ERC1155 and ERC721 tokens. Users need to trust the owner of the `ERC1155ERC721` contract.
* The owner of the `Cashier` contract can change the tokensContractAddress and the bosonRouterAddress. With this power the owner can take users' deposit funds. Users need to trust the owner of  `Cashier` contract.

If the contracts need to be non-upgradeable and trustless then the system needs to be changed so these addresses can't be changed once set, or some other design employed.

If the contracts can be upgradeable and trustful then I suggest using EIP-2535 Diamonds because it offers a standardized, scalable and flexible way to upgrade/extend a contract system in production.

The Boson documentation mentions it favors progressive decentralization. This can be achieved at the smart contract level in different ways concerning ownership/upgradeability/control of contracts. Here are some ways:
1. Deploy the Boson protocol contracts in production as a set of upgradeable contracts/diamond. Remove the ability to upgrade at some point.
2. Deploy the Boson protocol contracts in production as a set of upgradeable contracts/diamond controlled by the Boson team. In the future add a new part of the protocol that transfers control of upgrades to the Boson DAO so members of the Boson DAO can vote on-chain concerning upgrades to the protocol.  This way the smart contracts can enforce that upgrades on the protocol are only executed if they are approved by the Boson DAO.  This is [an approach DerivaDEX is using](https://medium.com/derivadex/the-diamond-standard-a-new-paradigm-for-upgradeability-569121a08954).

More variations of progressive decentralized control of the contracts could be implemented.   For example some admin functions could exist that change certain settings that are controlled by the Boson team.  Then in the future some or all of these admin functions could be turned over to the DAO's control.

### Implement ERC-173 Contract Ownership Standard

I suggest that contracts that have admin/owner functions like ERC1155ERC721 and Cashier implement ERC-173 Contract Ownership Standard. I made a separate issue about this here: #126

**Comment by thecryptofruit** [comment]
Thanks @mudgen !
@hswopeams is already checking point 2, and point 1 is a great suggestion (CC: @levalleux-ludo ).
Diamond is considered, likely for the next version.

**Comment by mudgen** [comment]
@hswopeams Sounds good, makes sense about plans for v0.2.0.

You are right, the contracts implement Ownable. I missed that. Just ERC1155ERC721 isn't but should implement Ownable.

As a note about upgradeable contracts,  or being able to change contract addresses:

Uniswap is a good example of a contract system that is immutable and trustless.   I think it is probably possible to make the Boson protocol immutable and trustless. Boson protocol is fundamentally an exchange.   But this would be a major part of the design to ensure it is immutable and trustless,  and would have less flexibility than being upgradeable or able to add or replace functionality incrementally, after deployment of course.

**Comment by cliffhall** [comment]
As we are currently preparing for a mainnet deployment tonight, I'm going to go ahead and close this. 

To the outstanding issue of ERC1155ERC721 implementing Ownable, we've refactored that contract into Vouchers and VoucherSets contracts, both implementing Ownable.
