### ISSUE TITLE
Implement ERC-173 Contract Ownership Standard

### ISSUE THREAD

**Issue by mudgen** [bosonprotocol/contracts#126]
I suggest that contracts that have admin/owner functions like `ERC1155ERC721` and `Cashier` implement [ERC-173](https://eips.ethereum.org/EIPS/eip-173).

Specifically implement this interface:
```
/// @title ERC-173 Contract Ownership Standard
///  Note: the ERC-165 identifier for this interface is 0x7f5828d0
interface ERC173 /* is ERC165 */ {
    /// @dev This emits when ownership of a contract changes.    
    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);

    /// @notice Get the address of the owner    
    /// @return The address of the owner.
    function owner() view external returns(address);
	
    /// @notice Set the address of the new owner of the contract
    /// @dev Set _newOwner to address(0) to renounce any ownership.
    /// @param _newOwner The address of the new owner of the contract    
    function transferOwnership(address _newOwner) external;	
}
```

The reason is because without an `transferOwnership` function the ownership of a contract can't be transferred from a developer account to a more secure account such as a multisig contract or possibly in the future a DAO contract.

I highly suggest that admin functions and upgrades and other powerful features be secured with a multisig contract such as one from [Gnosis Safe](https://gnosis-safe.io/), or DAO contract or other secure mechanism.

**Comment by hswopeams** [comment]
Cashier already implements OpenZeppeling Ownable. The ERC1155ERC721 does not yet. That needs to be added.
