### ISSUE TITLE
Review using Cryptographic Autonomous License

### ISSUE THREAD

**Issue by thecryptofruit** [bosonprotocol/contracts#17]
We need agreement on licensing. Currently happy with LGPL3, need to check Cryptographic Autonomous License, which has some protections for user data when cryptographic algorithms are involved (https://opensource.org/licenses/CAL-1.0).

_Originally posted by @RichardLitt in https://github.com/bosonprotocol/bsn-core-prototype/pull/15#discussion_r533873626_

**Comment by mischat** [comment]
We are happy with LGPL3 for now. Thanks for all the input on this...
