### ISSUE TITLE
Metadata storage, review ERC-2477

### ISSUE THREAD

**Issue by thecryptofruit** [bosonprotocol/contracts#20]
Could we use the metadata functionalities of erc1155 and erc721 to have these structured and easily accessible by others? Can create another issue for this.
See ERC-2477 metadata integration, too: https://github.com/ethereum/EIPs/issues/2483

_Originally posted by @thecryptofruit in https://github.com/bosonprotocol/bsn-core-prototype/pull/16#discussion_r532497821_

**Comment by cliffhall** [comment]
I think this is worth considering for v2. But that's another repo and project. Closing this one here.
