### ISSUE TITLE
Update cancelFaultPeriodStart on Redeem / Refund 

### ISSUE THREAD

**Issue by HristiyanG** [bosonprotocol/contracts#67]
As per the game tree, voucher paths can go as:

redeem - cancel - complain
redeem - complain - cancel
refund - cancel - complain
refund - complain - cancel

So we might consider setting the cancelFaultPeriodStart, while voucher is being redeemed / refunded as well?
More info how the system behaves right now from @thecryptofruit: 

```Currently the two clocks start ticking like so:
SETTING complainPeriodStart:
- at redeem()
- at refund()
- at cof(), when bit set at IDX_REDEEM||IDX_REFUND
- at cof(), when status is pure isCommitted
SETTING cancelFaultPeriodStart:
- at complain(), when status is pure isRedeem||isRefund
- at complain(), when status is pure isExpired

**Comment by mischat** [comment]
We did a make a change for this, addressed in v0.1
