### ISSUE TITLE
Check value of ERC-20 transfers in BosonRouter

### ISSUE THREAD

**Issue by thecryptofruit** [bosonprotocol/contracts#81]
Minor volatile code issue: `BosonRouter.sol` is not checking for return value of `transfer()` and `transferFrom()` of the ERC-20.
Reason: the contract has reached max size and needs refactoring.

Recommendation: user OpenZeppelin's `SafeERC20.sol`.

**Comment by mischat** [comment]
We will be looking at this internally, before making the public release of v0.2

**Comment by hswopeams** [comment]
Implemented in https://github.com/bosonprotocol/contracts/pull/149
