### ISSUE TITLE
Promise Key Creation

### ISSUE THREAD

**Issue by HristiyanG** [bosonprotocol/contracts#88]
While creating promise key for a voucher supply, we should include the address of the seller as well. it's possible that one might experience strange behaviour due to not hashing the seller's address

**Comment by hswopeams** [comment]
If this refers to VoucherKernel. createTokenSupplyID, I think we should add` address(this) `to the hash as well. Just to make sure multiple instances of the contract can't produce the same key.

**Comment by ali2251** [comment]
@HristiyanG  Can you elaborate on what the strange behaviour might be?

I am looking at this code:
```solidity
        bytes32 key =
            keccak256(
                abi.encodePacked(tokenNonces[_seller]++, _validFrom, _validTo)
            );

```

where this should make it unique:
```solidity
tokenNonces[_seller]++
```

Am I missing something?

**Comment by HristiyanG** [comment]
Assume that we have new deployed contracts. Right now, if I am to create a voucher-set (my nonce would be 0), and right after that a another user tries to create a voucher-set (his nonce will be 0 as well) with the same input parameters (startDate, endDate), you'll get an error `PROMISE_ALREADY_EXISTS`. We must avoid that

**Comment by mischat** [comment]
this is something we will look at in the v0.2-XXX release.

**Comment by hswopeams** [comment]
Change executed in PR 159. address(this) was added to the promise key generation to add uniqueness
