### ISSUE TITLE
GAS CONSUMPTION - ESTIMATION

### ISSUE THREAD

**Issue by sriharikapu** [bosonprotocol/contracts#99]
### Contract: `FundsLimitOracle`

CONTRCT | FUNCTION | GAS ESTIMATE
-- | -- | --
Fund Limits Oracle | setETHLimit | -
Fund Limits Oracle | setTokenLimit | -
Fund Limits Oracle | getETHLimit | 999
Fund Limits Oracle | getTokenLimit | 1165

### Contract: `ERC1155ERC721`

CONTRCT | FUNCTION | GAS ESTIMATE
-- | -- | --
ERC1155ERC721 | approve | 25174
ERC1155ERC721 | balanceOf | 1247
ERC1155ERC721 | OwnerOf | 1308
ERC1155ERC721 | setApprovalforAll | 23211
ERC1155ERC721 | isApprovedforAll | 1328
ERC1155ERC721 | setVoucherKernelAddress | 23329
ERC1155ERC721 | setBosonRouterAddress | 23374

### Contract: `VoucherKernel`

CONTRCT | FUNCTION | GAS ESTIMATE
-- | -- | --
Voucher Kernel | pause | 24789
Voucher Kernel | unpause | 24710
Voucher Kernel | createPaymentMethod | 44049
Voucher Kernel | generateTokenType | 21695
Voucher Kernel | setPaymentReleased | 24212
Voucher Kernel | setDepositsReleased | 24261
Voucher Kernel | setSupplyHolderOnTransfer | 23798
Voucher Kernel | getPromiseKey | 2044
Voucher Kernel | getIdSupplyFromVoucher | 336
Voucher Kernel | getPromiseIdFromVoucherId | 2182
Voucher Kernel | getOrderCosts | 3740
Voucher Kernel | getBuyerOrderCosts | 2958
Voucher Kernel | getSellerDeposit | 2043
Voucher Kernel | getVoucherStatus | 1372
Voucher Kernel | getSupplyHolder | 2136
Voucher Kernel | getVoucherPriceToken | 1267
Voucher Kernel | getVoucherDepositToken | 1241
Voucher Kernel | getVoucherPaymentMethod | 1212
Voucher Kernel | isInValidityPeriod | 9857
Voucher Kernel | isVoucherTransferable | 2134
Voucher Kernel | cancelOrFault | 44457
Voucher Kernel | triggerFinalizeVoucher | 44016
Voucher Kernel | setComplainPeriod | 14397
Voucher Kernel | setCancelFaultPeriod | 14375
Voucher Kernel | redeem | 78462
Voucher Kernel | refund | 66242
Voucher Kernel | createOrder | -
Voucher Kernel | fillOrder | -
Voucher Kernel | checkOrderFillable | -
Voucher Kernel | extract721 | -
Voucher Kernel | burnSupplyOnPause | -
Voucher Kernel | complain | -
Voucher Kernel | cancelOrFaultVoucherSet | -
Voucher Kernel | triggerExpiration | -
Voucher Kernel | setBosonRouterAddress | -
Voucher Kernel | setCashierAddress | -

### Contract: `Cashier`

CONTRCT | FUNCTION | GAS ESTIMATE
-- | -- | --
Cashier | pause | 24701
Cashier | unpause | 24664
Cashier | canunpause | 1052
Cashier | updateEscrowAmount | 22023
Cashier | updateEscrowTokensAmount | 22212
Cashier | getEscrowAmount | 78591
Cashier | requestCreateOrder | 359487
Cashier | requestVoucher | 175542
Cashier | getEscrowTokensAmount | -

### Contract: `BosonRouter`

CONTRCT | FUNCTION | GAS ESTIMATE
-- | -- | --
Boson Router | setTokenContractAddress | 23512

**Comment by mischat** [comment]
We will ensure that the ETH gas reporter is running and within our build tools. 

Thank for the report.
